alter session set current_schema = sys;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

DROP USER ad cascade;

CREATE user ad IDENTIFIED by 123;
GRANT CREATE SESSION TO ad container = all;
CONNECT ad/123;


GRANT EXECUTE ANY PROCEDURE TO ad; 
GRANT ALL PRIVILEGES TO ad;

Grant SYSDBA TO AD;

GRANT INHERIT PRIVILEGES ON USER sys TO ad;