BEGIN
    SA_SYSDBA.DROP_POLICY(
        policy_name     => 'notification_policy',
        drop_column     => TRUE
    );
END;
/

--BEGIN
--    SA_SYSDBA.DROP_POLICY(
--        policy_name     => 'nhansu_policy',
--        drop_column     => TRUE
--    );
--END;
--/

BEGIN 
    SA_SYSDBA.CREATE_POLICY( 
    policy_name => 'notification_policy',  
    column_name => 'notification_label' 
    ); 
END;

BEGIN
    SA_SYSDBA.DROP_POLICY(
        policy_name => 'notification_policy',  -- replace with your policy name
        drop_column=> true
    );
END;

EXEC SA_SYSDBA.ENABLE_POLICY ('NOTIFICATION_POLICY'); 

-- create level
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',120,'TK', 'TRUONG KHOA'); 
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',100,'TDV','TRUONG DON VI'); 
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',80,'GVN','GIAO VIEN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',60,'GV','GIAO VU');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',40,'NV','NHAN VIEN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',20,'SV','SINH VIEN');

-- create compartment
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',5,'HTTT','HE THONG THONG TIN'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',10,'CNPM','CONG NGHE PHAN MEM'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',15,'KHMT','KHOA HOC MAY TINH'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',20,'CNTT','CONG NGHE THONG TIN'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',25,'TGMT','THI GIAC MAY TINH'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',30,'MMT','MANG MAY TINH'); 

-- create group
EXECUTE SA_COMPONENTS.CREATE_GROUP('notification_policy',10,'CS1','CO SO 1'); 
EXECUTE SA_COMPONENTS.CREATE_GROUP('notification_policy',15,'CS2','CO SO 2');

BEGIN 
SA_SYSDBA.CREATE_POLICY( 
policy_name => 'nhansu_policy',  
column_name => 'nhansu_label' 
); 
END;

EXEC SA_SYSDBA.ENABLE_POLICY ('nhansu_policy'); 

EXECUTE SA_COMPONENTS.CREATE_LEVEL('nhansu_policy',120,'TK', 'TRUONG KHOA'); 
EXECUTE SA_COMPONENTS.CREATE_LEVEL('nhansu_policy',100,'TDV','TRUONG DON VI'); 
EXECUTE SA_COMPONENTS.CREATE_LEVEL('nhansu_policy',80,'GVN','GIAO VIEN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('nhansu_policy',60,'GV','GIAO VU');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('nhansu_policy',40,'NV','NHAN VIEN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('nhansu_policy',20,'SV','SINH VIEN');

-- create compartment
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('nhansu_policy',5,'HTTT','HE THONG THONG TIN'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('nhansu_policy',10,'CNPM','CONG NGHE PHAN MEM'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('nhansu_policy',15,'KHMT','KHOA HOC MAY TINH'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('nhansu_policy',20,'CNTT','CONG NGHE THONG TIN'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('nhansu_policy',25,'TGMT','THI GIAC MAY TINH'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('nhansu_policy',30,'MMT','MANG MAY TINH'); 

-- create group
EXECUTE SA_COMPONENTS.CREATE_GROUP('nhansu_policy',10,'CS1','CO SO 1'); 
EXECUTE SA_COMPONENTS.CREATE_GROUP('nhansu_policy',15,'CS2','CO SO 2');

--create table NHANSU_OLS
--(
--    MANV CHAR(5),
--    HOTEN nvarchar2(30),
--    VAITRO nvarchar2(20),
--    COSO NVARCHAR2(10),
--    
--    PRIMARY KEY (MANV),
--    constraint NHANSU_Phai check (PHAI = N'Nam' OR PHAI = N'Nữ')
--);

--CREATE TABLE SINHVIEN_OLS (
--    MASV CHAR(6),
--    HOTEN NVARCHAR2(30),
--    MANGANH VARCHAR2(10),
--    COSO NVARCHAR2(10),
--    
--    PRIMARY KEY (MASV)
--);

create table NHANSU_OLS
(
    MANV CHAR(5),
    VAITRO nvarchar2(20),
    MADV CHAR(4),
    COSO NVARCHAR2(10),
    
    PRIMARY KEY (MANV)
);

create table THONGBAO_OLS
(
    MATB CHAR(5),
    NOIDUNG NVARCHAR2(200),
    VAITRO nvarchar2(20),
    MADV CHAR(4),
    COSO NVARCHAR2(10),
    
    PRIMARY KEY (MATB)
);

--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'TK');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'TDV:HTTT:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'TDV:HTTT:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'TDV:CNPM:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'TDV:CNPM:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'TDV:KHMT:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'TDV:KHMT:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'TDV:CNTT:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'TDV:CNTT:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'TDV:TGMT:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'TDV:TGMT:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'TDV:MMT:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'TDV:MMT:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'GVN:HTTT:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'GVN:HTTT:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'GVN:CNPM:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'GVN:CNPM:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'GVN:KHMT:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'GVN:KHMT:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'GVN:CNTT:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'GVN:CNTT:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'GVN:TGMT:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'GVN:TGMT:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'GVN:MMT:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'GVN:MMT:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'GV:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'GV:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'NV:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'NV:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'SV:HTTT:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'SV:HTTT:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'SV:CNPM:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'SV:CNPM:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'SV:KHMT:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'SV:KHMT:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'SV:CNTT:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'SV:CNTT:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'SV:TGMT:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'SV:TGMT:CS2');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'SV:MMT:CS1');
--EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', '100', 'SV:MMT:CS2');


-- CHECK
SELECT * FROM DBA_SA_LEVELS; 
SELECT * FROM DBA_SA_COMPARTMENTS; 
SELECT * FROM DBA_SA_GROUPS; 
SELECT * FROM DBA_SA_GROUP_HIERARCHY; 

-- CREATE LABEL
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TK') 
WHERE ID = 1; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:HTTT:CS1') 
WHERE ID = 2; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:CNPM:CS1') 
WHERE ID = 3; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:KHMT:CS1') 
WHERE ID = 4; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:CNTT:CS1') 
WHERE ID = 5; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:TGMT:CS1') 
WHERE ID = 6; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:MMT:CS1') 
WHERE ID = 7; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:HTTT:CS2') 
WHERE ID = 8; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:CNPM:CS2') 
WHERE ID = 9; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:KHMT:CS2') 
WHERE ID = 10; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:CNTT:CS2') 
WHERE ID = 11; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:TGMT:CS2') 
WHERE ID = 12; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:MMT:CS2') 
WHERE ID = 13; 

UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:HTTT:CS1') 
WHERE ID = 14; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:CNPM:CS1') 
WHERE ID = 15; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:KHMT:CS1') 
WHERE ID = 16; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:CNTT:CS1') 
WHERE ID = 17; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:TGMT:CS1') 
WHERE ID = 18; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:MMT:CS1') 
WHERE ID = 19; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:HTTT:CS2') 
WHERE ID = 20; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:CNPM:CS2') 
WHERE ID = 21; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:KHMT:CS2') 
WHERE ID = 22; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:CNTT:CS2') 
WHERE ID = 23; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:TGMT:CS2') 
WHERE ID = 24; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:MMT:CS2') 
WHERE ID = 25;

UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GV:CS1') 
WHERE ID = 26; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GV:CS2') 
WHERE ID = 27;

UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','NV:CS1') 
WHERE ID = 28; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','NV:CS2') 
WHERE ID = 29;

UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:HTTT:CS1') 
WHERE ID = 30; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:CNPM:CS1') 
WHERE ID = 31; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:KHMT:CS1') 
WHERE ID = 32; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:CNTT:CS1') 
WHERE ID = 33; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:TGMT:CS1') 
WHERE ID = 34; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:MMT:CS1') 
WHERE ID = 35; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:HTTT:CS2') 
WHERE ID = 36; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:CNPM:CS2') 
WHERE ID = 37; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:KHMT:CS2') 
WHERE ID = 38; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:CNTT:CS2') 
WHERE ID = 39; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:TGMT:CS2') 
WHERE ID = 40; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:MMT:CS2') 
WHERE ID = 41;