
BEGIN 
    SA_SYSDBA.CREATE_POLICY( 
    policy_name => 'notification_policy',  
    column_name => 'notification_label' 
    ); 
END;

BEGIN
    SA_SYSDBA.DROP_POLICY(
        policy_name => 'notification_policy',  -- replace with your policy name
        drop_column=> true
    );
END;

EXEC SA_SYSDBA.ENABLE_POLICY ('notification_policy'); 

-- create level
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',300,'TK', 'TRUONG KHOA'); 
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',250,'TDV','TRUONG DON VI'); 
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',200,'GVN','GIAO VIEN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',150,'GV','GIAO VU');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',100,'NV','NHAN VIEN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',50,'SV','SINH VIEN');

-- create compartment
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',5,'HTTT','HE THONG THONG TIN'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',10,'CNPM','CONG NGHE PHAN MEM'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',15,'KHMT','KHOA HOC MAY TINH'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',20,'CNTT','CONG NGHE THONG TIN'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',25,'TGMT','THI GIAC MAY TINH'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',30,'MMT','MANG MAY TINH'); 

-- create group
EXECUTE SA_COMPONENTS.CREATE_GROUP('notification_policy',10,'CS1','CO SO 1'); 
EXECUTE SA_COMPONENTS.CREATE_GROUP('notification_policy',15,'CS2','CO SO 2');

CREATE TABLE SINHVIEN_OLS (
    MASV CHAR(6),
    HOTEN NVARCHAR2(30),
    MANGANH VARCHAR2(10),
    COSO NVARCHAR2(10),
    
    PRIMARY KEY (MASV)
);

create table NHANSU_OLS
(
    MANV CHAR(5),
    VAITRO nvarchar2(20),
    MADV CHAR(4),
    COSO NVARCHAR2(10),
    
    PRIMARY KEY (MANV)
);

--DROP TABLE NHANSU_OLS;

INSERT INTO NHANSU_OLS(MANV, VAITRO, MADV, COSO) VALUES('NV001', 'TK', null, null);
INSERT INTO NHANSU_OLS(MANV, VAITRO, MADV, COSO) VALUES('NV002', 'TDV', NULL, 'CS2');
INSERT INTO NHANSU_OLS(MANV, VAITRO, MADV, COSO) VALUES('NV003', 'GV', NULL, NULL);
INSERT INTO NHANSU_OLS(MANV, VAITRO, MADV, COSO) VALUES('NV004', 'TDV', NULL, NULL);
INSERT INTO NHANSU_OLS(MANV, VAITRO, MADV, COSO) VALUES('NV005', 'SV', 'HTTT', 'CS1');
INSERT INTO NHANSU_OLS(MANV, VAITRO, MADV, COSO) VALUES('NV006', 'TDV', 'KHMT', 'CS1');
INSERT INTO NHANSU_OLS(MANV, VAITRO, MADV, COSO) VALUES('NV007', 'TDV', 'KHMT', 'CS1');
INSERT INTO NHANSU_OLS(MANV, VAITRO, MADV, COSO) VALUES('NV008', 'GV', 'KHMT', 'CS2');
INSERT INTO NHANSU_OLS(MANV, VAITRO, MADV, COSO) VALUES('NV009', 'SV', 'HTTT', 'CS1');
iNSERT INTO NHANSU_OLS(MANV, VAITRO, MADV, COSO) VALUES('NV010', 'GV', 'HTTT', 'CS1');
CREATE USER NV001 IDENTIFIED BY 123;
CREATE USER NV002 IDENTIFIED BY 123;
CREATE USER NV003 IDENTIFIED BY 123;
CREATE USER NV004 IDENTIFIED BY 123;
CREATE USER NV005 IDENTIFIED BY 123;
CREATE USER NV006 IDENTIFIED BY 123;
CREATE USER NV007 IDENTIFIED BY 123;
CREATE USER NV008 IDENTIFIED BY 123;
CREATE USER NV009 IDENTIFIED BY 123;
CREATE USER NV010 IDENTIFIED BY 123;

GRANT CONNECT TO NV001, NV002, NV003, NV004, NV005, NV006, NV007, NV008, NV009, NV010;
GRANT SELECT ON ADMIN_OLS.THONGBAO_OLS TO NV001, NV002, NV003, NV004, NV005, NV006, NV007, NV008, NV009, NV010;

--SELECT * FROM USER_POLICIES;

-- CHECK
--SELECT * FROM DBA_SA_LEVELS; 
--SELECT * FROM DBA_SA_COMPARTMENTS; 
--SELECT * FROM DBA_SA_GROUPS; 
--SELECT * FROM DBA_SA_GROUP_HIERARCHY;   

SELECT * FROM ALL_SA_LABELS;

SELECT * FROM ADMIN_OLS.THONGBAO_OLS;

BEGIN
 SA_USER_ADMIN.SET_USER_LABELS('notification_policy','NV001','TK:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2');
 SA_USER_ADMIN.SET_USER_LABELS(
      policy_name    => 'notification_policy',
      user_name      => 'NV002', 
      max_read_label => 'TDV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2');
 SA_USER_ADMIN.SET_USER_LABELS('notification_policy','NV003','GV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2');
 SA_USER_ADMIN.SET_USER_LABELS('notification_policy','NV004','TDV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2');
 SA_USER_ADMIN.SET_USER_LABELS('notification_policy','NV005','SV:HTTT:CS1');
 SA_USER_ADMIN.SET_USER_LABELS('notification_policy','NV006','TDV:KHMT:CS1');
 SA_USER_ADMIN.SET_USER_LABELS('notification_policy','NV007','TDV:KHMT:CS1,CS2');
 SA_USER_ADMIN.SET_USER_LABELS('notification_policy','NV008','GVN:HTTT:CS1,CS2');
 SA_USER_ADMIN.SET_USER_LABELS('notification_policy','NV009','SV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2');
 SA_USER_ADMIN.SET_USER_LABELS('notification_policy','NV010','GVN:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2');
END; 

create table THONGBAO_OLS
(
    MATB CHAR(5),
    NOIDUNG NVARCHAR2(200),
    VAITRO nvarchar2(4),
    MADV CHAR(4),
    COSO NVARCHAR2(4),
    
    PRIMARY KEY (MATB)
);

--delete from ADMIN_OLS.THONGBAO_OLS;

INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0001', 'Thông báo 1 - nội dung mẫu', 'TK', 'HTTT', 'CS1');
INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0002', 'Thông báo 2 - nội dung khác', 'TK', 'HTTT', 'CS2');
INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0003', 'Thông báo 3 - nội dung khác', 'TK', NULL, NULL);
INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0004', 'Thông báo 4 - nội dung khác', 'TK', 'KHMT', NULL);
INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0005', 'Thông báo 5 - nội dung mẫu', 'TDV', 'HTTT', 'CS1');
INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0006', 'Thông báo 6 - nội dung khác', 'TDV', 'HTTT', 'CS2');
INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0007', 'Thông báo 7 - nội dung khác', 'TDV', 'KHMT', NULL);
INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0008', 'Thông báo 8 - nội dung khác', 'GV', NULL, NULL);
INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0009', 'Thông báo 9 - nội dung mẫu', 'GV', 'HTTT', 'CS1');
INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0010', 'Thông báo 10 - nội dung khác', 'TDV', NULL, NULL);
INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0011', 'Thông báo 11 - nội dung khác', 'SV', 'HTTT', 'CS1');
INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0012', 'Thông báo 12 - nội dung khác', 'SV', 'KHMT', 'CS1');
INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0013', 'Thông báo 13 - nội dung mẫu', 'TDV', 'KHMT', 'CS1');
INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0014', 'Thông báo 14 - nội dung khác', 'TDV', 'HTTT', 'CS1');
INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0015', 'Thông báo 15 - nội dung khác', 'TDV', 'KHMT', 'CS2');
INSERT INTO ADMIN_OLS.THONGBAO_OLS (MATB, NOIDUNG, VAITRO, MADV, COSO)
VALUES ('A0016', 'Thông báo 16 - nội dung khác', 'TDV', 'HTTT', 'CS2');

BEGIN
 SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('notification_policy', 'admin_ols', 'THONGBAO_OLS');
 SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
 POLICY_NAME => 'NOTIFICATION_POLICY',
 SCHEMA_NAME => 'ADMIN_OLS',
 TABLE_NAME => 'THONGBAO_OLS',
 TABLE_OPTIONS => 'NO_CONTROL'
 );
END; 

BEGIN
    SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('notification_policy', 'admin_ols', 'THONGBAO_OLS');
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
        policy_name    => 'notification_policy',
        schema_name    => 'ADMIN_OLS', 
        table_name     => 'THONGBAO_OLS',
        table_options  => 'READ_CONTROL',
        label_function => 'ADMIN_OLS.gen_notification_label(:new.VAITRO,:new.MADV,:new.COSO)',
        predicate => NULL
    );
END;
/

CREATE OR REPLACE FUNCTION gen_notification_label(VAITRO VARCHAR2, MADV VARCHAR2, COSO VARCHAR2)
RETURN lbacsys.lbac_label AS
label VARCHAR2(30);
BEGIN
    label := VAITRO || ':' || MADV || ':' || COSO;
    RETURN to_lbac_data_label('notification_policy', label);
END;
/

GRANT EXECUTE ON gen_notification_label TO PUBLIC;



